# Site settings
title: Zac Kenton
email: zakenton@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a PhD Candidate at Queen Mary University of London.
  I am a mathematician, physicist and computer scientist.
  My main interest is now in Machine Learning.
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://zackenton.github.io/" # the base hostname & protocol for your site
twitter_username: ZacKenton1
github_username:  zackenton
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
